Practical Assignment - Programming for Data Analysis 2018

# 1. Overall purpose of the package

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Numpy.random subpackage has the ability to generate randomness of data, shuffle existing data and draw samples based on a specified distribution.

# 2.1. Simple Random Data

# Random.random()
Returns random floats in the interval between 0 and 1.

In [6]:
a = np.random.random() # 1 number -  is nothing specified

In [7]:
a

0.37684120408083766

In [8]:
b = np.random.random(3) # array of 3 numbers specified

In [9]:
b

array([0.88659391, 0.33111906, 0.1370819 ])

In [29]:
c = np.random.random((3,2)) # array of 3 rows and 2 columns specified

In [30]:
c

array([[0.98908417, 0.68075188],
       [0.70737277, 0.56644664],
       [0.42631481, 0.46453879]])

In [41]:
c_50 = 50*c

In [42]:
c_50   # random floats between 0 an 50 are generated

array([[49.45420841, 34.03759379],
       [35.36863875, 28.32233206],
       [21.31574062, 23.22693945]])

# Random.rand()
Generates random values from 0 to 1 in the specified shape

In [15]:
d = np.random.rand()  # 1 number -  is nothing specified

In [16]:
d

0.0415347216341968

In [18]:
e = np.random.random(3) # array of 3 numbers specified

In [19]:
e

array([0.09500665, 0.46408814, 0.59428784])

In [25]:
f = np.random.rand(3,2) # array of 3 rows and 2 columns specified

In [26]:
f

array([[0.60777773, 0.84775328],
       [0.93107525, 0.820833  ],
       [0.54808679, 0.0126368 ]])

# Random.randn()
Generates random values from -1 to 1 in the specified shape

In [31]:
g = np.random.randn(3,2) # array of 3 rows and 2 columns specified

In [32]:
g

array([[-0.09905096,  1.16266363],
       [ 0.87010246, -1.71769179],
       [-0.19237741,  1.19196476]])

# Random.randint()
Generates random integers from low (inclusive) to high (exclusive)

In [33]:
h = np.random.randint(1,7) # will return a random integer between 1 and 6

In [34]:
h

3

In [35]:
i = np.random.randint(1,7,size=3) # size specified - will return a random integer between 1 and 6 three times and will wrap it into an array

In [36]:
i

array([5, 5, 2])

In [39]:
j = np.random.randint(1,7,size=(3,2)) # size specified - 2 rows by 3 columns

In [40]:
j

array([[6, 3],
       [4, 6],
       [6, 5]])

# Random.sample() function
Generates a particular length list of items chosen from the 
sequence. Can be a list, tuple, string or set. Random sub-library needs to be imported first.

In [58]:
import random

# Print list of random items of length 3 from the given list. 
numbers = [1, 63, 27, 28, 93, 411]
print("List output:", random.sample(numbers, 3)) 
  
# Print list of random items of length 4 from the given string.  
string = "Emptiness"
print("String output:", random.sample(string, 4)) 
     
# Print list of random items of length 3 from the given set. 
set = {"a", "b", "c", "d", "e","f","g","h","i"} 
print("Set output:", random.sample(set1, 5))

# Print list of random items of length 2 from the given tuple. 
cars = ("Mazda" , "Honda" , "VW" , "BMW" , "Mercedes") 
print("Tuple output:", random.sample(cars, 3)) 

List output: [1, 93, 63]
String output: ['s', 't', 'p', 'e']
Set output: ['c', 'b', 'd', 'e', 'a']
Tuple output: ['Mercedes', 'BMW', 'VW']
